ustawienia:
  numerIndeksu: 22222
  wycena: "CENY_BEZ_ZMIAN"
  zamowienia: "POJEDYNCZE"
  zaopatrzenie: "POJEDYNCZE"
  wydarzenia: "WYCOFANIE"
  liczbaZadan: 200
  redisHost: "150.254.68.196"
  redisPort: 8989
