spring:
  redis:
    host: localhost
    port: 6379

ustawienia:
  numerIndeksu: 287046
  wycena: "CENY_BEZ_ZMIAN"
  zamowienia: "POJEDYNCZE"
  zaopatrzenie: "POJEDYNCZE"
  wydarzenia: "WYCOFANIE"
  liczbaZadan: 200
